"""LLM-powered intent parsing for natural language environment requests."""

from __future__ import annotations

import json
from dataclasses import dataclass, field

from ai_engineering_bootstrap.agent.provider import LLMProvider
from ai_engineering_bootstrap.environment.models import EnvironmentRequest
from ai_engineering_bootstrap.environment.tool_catalog import ToolCatalog


@dataclass
class ParsedIntent:
    """Structured intent extracted from natural language."""

    natural_language_goal: str = ""
    required_tools: list[str] = field(default_factory=list)
    optional_tools: list[str] = field(default_factory=list)
    languages: list[str] = field(default_factory=list)
    frameworks: list[str] = field(default_factory=list)
    project_dependencies: list[str] = field(default_factory=list)
    constraints: list[str] = field(default_factory=list)
    platform_preferences: list[str] = field(default_factory=list)
    confidence: float = 0.0
    reasoning_summary: str = ""

    def to_environment_request(
        self,
        project_path: str,
        project_id: str | None = None,
    ) -> EnvironmentRequest:
        """Convert parsed intent into a structured EnvironmentRequest."""
        return EnvironmentRequest(
            request_id="",  # Will be generated by EnvironmentRequest
            project_id=project_id or "",
            project_path=project_path,
            natural_language_goal=self.natural_language_goal,
            required_tools=self.required_tools,
            optional_tools=self.optional_tools,
            languages=self.languages,
            frameworks=self.frameworks,
            project_dependencies=self.project_dependencies,
            configurations={},
            constraints=self.constraints,
            platform_preferences=self.platform_preferences,
            user_preferences={},
        )


class IntentParser:
    """Parse natural language into structured environment requests."""

    def __init__(self, provider: LLMProvider | None = None, tool_catalog: ToolCatalog | None = None) -> None:
        self.provider = provider
        self.tool_catalog = tool_catalog
        self._known_tools = set()
        if tool_catalog:
            for tool in tool_catalog.list_tools():
                self._known_tools.add(tool.tool_id)
        else:
            # Fallback to default known tools
            self._known_tools = {
                "python",
                "git",
                "cursor",
                "docker",
                "ruff",
                "black",
                "pytest",
                "github-cli",
                "nodejs",
                "npm",
                "uv",
                "poetry",
            }
        self._known_frameworks = {
            "fastapi",
            "flask",
            "django",
            "pytorch",
            "tensorflow",
            "transformers",
            "langchain",
            "llama-index",
            "react",
            "vue",
            "angular",
        }

    def is_llm_available(self) -> bool:
        """Check if LLM provider is available."""
        return self.provider is not None

    def parse(self, natural_language: str) -> ParsedIntent:
        """
        Parse natural language goal into structured intent.

        Args:
            natural_language: User's natural language description

        Returns:
            ParsedIntent with structured fields
        """
        if not self.provider:
            # Fallback: deterministic parsing
            return self._deterministic_parse(natural_language)

        try:
            return self._llm_parse(natural_language)
        except Exception:
            # Fallback to deterministic on any LLM failure
            return self._deterministic_parse(natural_language)

    def _llm_parse(self, natural_language: str) -> ParsedIntent:
        """Use LLM to parse intent."""
        prompt = self._build_prompt(natural_language)

        # We're not selecting capabilities here, just parsing
        decision = self.provider.decide(prompt, [])

        # Extract structured data from reasoning_summary or metadata
        try:
            # Try to parse JSON from reasoning_summary
            content = decision.reasoning_summary.strip()
            if content.startswith("```json"):
                content = content[7:].strip()
            if content.endswith("```"):
                content = content[:-3].strip()

            parsed = json.loads(content)
            return ParsedIntent(
                natural_language_goal=parsed.get(
                    "natural_language_goal", natural_language
                ),
                required_tools=parsed.get("required_tools", []),
                optional_tools=parsed.get("optional_tools", []),
                languages=parsed.get("languages", []),
                frameworks=parsed.get("frameworks", []),
                project_dependencies=parsed.get("project_dependencies", []),
                constraints=parsed.get("constraints", []),
                platform_preferences=parsed.get("platform_preferences", []),
                confidence=decision.confidence,
                reasoning_summary="LLM-parsed intent",
            )
        except (json.JSONDecodeError, KeyError):
            # Fallback if JSON parsing fails
            return self._deterministic_parse(natural_language)

    def _deterministic_parse(self, natural_language: str) -> ParsedIntent:
        """Deterministic fallback parsing using keyword matching."""
        text_lower = natural_language.lower()

        required_tools = []
        optional_tools = []
        languages = []
        frameworks = []
        dependencies = []
        constraints = []

        # Detect tools
        for tool in self._known_tools:
            if tool in text_lower:
                required_tools.append(tool)

        # Detect frameworks
        for framework in self._known_frameworks:
            if framework in text_lower:
                frameworks.append(framework)

        # Detect languages
        if "python" in text_lower:
            languages.append("python")
        if "javascript" in text_lower or "js" in text_lower:
            languages.append("javascript")
        if "typescript" in text_lower or "ts" in text_lower:
            languages.append("typescript")

        # Detect common constraints
        if "no sudo" in text_lower or "without root" in text_lower:
            constraints.append("no_root_required")
        if "virtualenv" in text_lower or "venv" in text_lower:
            constraints.append("use_virtualenv")
        if "isolated" in text_lower:
            constraints.append("isolated_environment")

        # Heuristic: if "AI" or "ML" mentioned, add common tools
        if "ai" in text_lower or "ml" in text_lower or "machine learning" in text_lower:
            if "python" not in required_tools:
                required_tools.append("python")
            if "pytorch" not in frameworks and "tensorflow" not in frameworks:
                frameworks.append("pytorch")
            if "transformers" not in frameworks:
                frameworks.append("transformers")

        # Heuristic: if "FastAPI" mentioned, add related tools
        if "fastapi" in text_lower:
            if "python" not in required_tools:
                required_tools.append("python")
            if "uvicorn" not in dependencies:
                dependencies.append("uvicorn")
            if "pytest" not in required_tools:
                required_tools.append("pytest")

        return ParsedIntent(
            natural_language_goal=natural_language,
            required_tools=required_tools,
            optional_tools=optional_tools,
            languages=languages,
            frameworks=frameworks,
            project_dependencies=dependencies,
            constraints=constraints,
            confidence=0.7,  # Lower confidence for deterministic parsing
            reasoning_summary="Deterministic keyword-based parsing",
        )

    def _build_prompt(self, natural_language: str) -> str:
        """Build prompt for LLM intent parsing."""
        return f"""You are an intent parser for engineering environment setup.

Given a natural language goal, extract structured information about:
- Required tools (essential for the environment)
- Optional tools (nice to have)
- Programming languages
- Frameworks
- Project dependencies
- Constraints (e.g., no root, isolated environment)

Respond with ONLY valid JSON in this exact format:
{{
    "natural_language_goal": "...",
    "required_tools": ["tool1", "tool2"],
    "optional_tools": ["tool3"],
    "languages": ["python"],
    "frameworks": ["fastapi", "pytorch"],
    "project_dependencies": ["package1"],
    "constraints": ["no_root_required"],
    "platform_preferences": ["linux"]
}}

User goal: {natural_language}

/no_think"""


__all__ = ["IntentParser", "ParsedIntent"]
