"""Environment models for AI Engineering Bootstrap."""

from .installation_strategies import (
    ArtifactMetadata,
    BinaryInstallStrategy,
    DebInstallStrategy,
    InstallationResult,
    InstallationStrategyBase,
    PipInstallStrategy,
    StrategyFactory,
    get_current_platform,
)
from .models import (
    ActualEnvironmentState,
    DeltaAction,
    DesiredEnvironmentState,
    EnvironmentDelta,
    EnvironmentRequest,
    PackageDelta,
    PythonPackageRequirement,
    ToolDelta,
    ToolRequirement,
    ToolRequirementLevel,
    ToolStatus,
)
from .reconciler import EnvironmentReconciler
from .session_models import (
    AgentDecision,
    EnvironmentSession,
    SessionEvent,
    SessionStatus,
)
from .session_store import SessionStore
from .tool_catalog import (
    Architecture,
    ArtifactFormat,
    DuplicateToolError,
    InstallationStrategy,
    Platform,
    PrivilegeLevel,
    ProbeDefinition,
    RiskLevel,
    ToolCatalog,
    ToolDefinition,
    get_tool_catalog,
)

__all__ = [
    "ActualEnvironmentState",
    "AgentDecision",
    "Architecture",
    "ArtifactFormat",
    "ArtifactMetadata",
    "BinaryInstallStrategy",
    "DebInstallStrategy",
    "DeltaAction",
    "DesiredEnvironmentState",
    "DuplicateToolError",
    "EnvironmentDelta",
    "EnvironmentReconciler",
    "EnvironmentRequest",
    "EnvironmentSession",
    "InstallationResult",
    "InstallationStrategy",
    "InstallationStrategyBase",
    "PackageDelta",
    "PipInstallStrategy",
    "Platform",
    "PrivilegeLevel",
    "ProbeDefinition",
    "PythonPackageRequirement",
    "RiskLevel",
    "SessionEvent",
    "SessionStatus",
    "SessionStore",
    "StrategyFactory",
    "ToolCatalog",
    "ToolDefinition",
    "ToolDelta",
    "ToolRequirement",
    "ToolRequirementLevel",
    "ToolStatus",
    "get_current_platform",
    "get_tool_catalog",
]
